---
- name: Install docker and DVWA
  hosts: webservers
  become: true
  tasks:

  - name: Install Docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip
    apt:
      name: python3-pip
      state: present

  - name: Install docker python container
    pip:
      name: docker
      state: present

  - name: Download and launch DVWA container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
